### ISSUE TITLE
Upload fails - no attribute IntFlag

### ISSUE THREAD

**Issue by vanvuongngo** [sipeed/platform-kendryte210#27]
Upload firmware with `platform.io` fails. Upload with `kflash_gui` is working.

Platform.io version: Core 4.3.4, Home 3.2.3
Kendryte K210 platform version: 1.2.2

platform.ini
```
[env:sipeed-maix-go]
platform = kendryte210
board = sipeed-maix-go
framework = arduino

; serial monitor baudrate
monitor_speed = 115200

upload_port = /dev/ttyUSB1
```

Upload - Error:
```
Use manually specified: /dev/ttyUSB1
Uploading .pio/build/sipeed-maix-go/firmware.bin
Traceback (most recent call last):
  File ".platformio/packages/tool-kflash-kendryte210/kflash.py", line 13, in <module>
    import argparse
  File "/usr/lib/python3.8/argparse.py", line 88, in <module>
    import re as _re
  File ".platformio/penv/lib/python3.8/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
*** [upload] Error 1
======================================= [FAILED] Took 3.11 seconds =======================================
The terminal process "platformio 'run', '--target', 'upload'" terminated with exit code: 1.
```

**Comment by vanvuongngo** [comment]
same issue: https://github.com/sipeed/platform-kendryte210/issues/19

**Comment by vanvuongngo** [comment]
I deleted the `enum` folder and now it works fine.
